## Linter GitHub Actions
name: "Lint Code Base ğŸ”  "

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

# Start the job on all push
on:
  push:
    branches:
      - master
  pull_request:

# Set the Job
jobs:
  lint_code:
    # Name the Job
    name: ğŸ” Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps
    steps:
      # Checkout the code base
      - name: ğŸ” Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      # Run Linter against code base #
      - name: ğŸ”  Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
